spring.application.name=Rental
spring.datasource.url=jdbc:mysql://localhost:3306/Rental_db
spring.datasource.username=root
spring.datasource.password=bca1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

